In [166]:
import pandas as pd

In [167]:
df = pd.read_csv('laptop_data.csv')     ## df=data frame

In [168]:
df.duplicated().sum()  ## check for duplicate rows

np.int64(0)

In [169]:
df.shape

(1303, 12)

In [170]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [171]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [172]:
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [173]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)  ## convert the Ram column to int type
df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)  ## convert the Weight column to float type
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.80,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.30,79866.7200
1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.50,12201.1200
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.20,19660.3200

In [174]:
char = df.select_dtypes(include=['object', 'str'])  ## select_dtypes is used to select the data type of the column. Here we are selecting the object data type columns.

In [175]:
num=df.select_dtypes(exclude=['object'])  ## select_dtypes is used to select the data type of the column. Here we are selecting the int64 and float64 data type columns.

In [176]:
num

      Inches  Ram  Weight        Price
0       13.3    8    1.37   71378.6832
1       13.3    8    1.34   47895.5232
2       15.6    8    1.86   30636.0000
3       15.4   16    1.83  135195.3360
4       13.3    8    1.37   96095.8080
...      ...  ...     ...          ...
1298    14.0    4    1.80   33992.6400
1299    13.3   16    1.30   79866.7200
1300    14.0    2    1.50   12201.1200
1301    15.6    6    2.19   40705.9200
1302    15.6    4    2.20   19660.3200

[1303 rows x 4 columns]

In [177]:
char

,Company,TypeName,ScreenResolution,Cpu,Memory,Gpu,OpSys
0,Apple,Ultrabook,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,128GB SSD,Intel Iris Plus Graphics 640,macOS
1,Apple,Ultrabook,1440x900,Intel Core i5 1.8GHz,128GB Flash Storage,Intel HD Graphics 6000,macOS
2,HP,Notebook,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,256GB SSD,Intel HD Graphics 620,No OS
3,Apple,Ultrabook,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,512GB SSD,AMD Radeon Pro 455,macOS
4,Apple,Ultrabook,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,256GB SSD,Intel Iris Plus Graphics 650,macOS
...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,128GB SSD,Intel HD Graphics 520,Windows 10
1299,Lenovo,2 in 1 Convertible,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,512GB SSD,Intel HD Graphics 520,Windows 10
1300,Lenovo,Notebook,1366x768,Intel Celeron Dual Core N3050 1.6GHz,64GB Flash Storage,Intel HD Graphics,Windows 10
1301,HP,Notebook,1366x768,Intel Core i7 6500U 2.5GHz,1TB HDD,AMD Radeon R5 M330,Windows 10
1302,Asus,Notebook,1366x768,Intel Celeron Dual Core N3050 1.6GHz,500GB HDD,Intel HD Graphics,Windows 10

In [178]:
char['OpSys'].unique

<bound method Series.unique of 0            macOS
1            macOS
2            No OS
3            macOS
4            macOS
           ...
1298    Windows 10
1299    Windows 10
1300    Windows 10
1301    Windows 10
1302    Windows 10
Name: OpSys, Length: 1303, dtype: str>

In [179]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\Devansh\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Devansh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Devansh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\Devansh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Devansh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Devansh\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [180]:
from sklearn.preprocessing import LabelEncoder ##its used for factorization of the categorical data
le = LabelEncoder()
char['ScreenResolution'] = le.fit_transform(char['ScreenResolution'])

In [181]:
import joblib
joblib.dump(le ,"screen_resolution_encoder.lib")

['screen_resolution_encoder.lib']

In [182]:
# Create unique encoder
le_cpu = LabelEncoder()
# Transform data
char['Cpu'] = le_cpu.fit_transform(char['Cpu'])
# Save file
joblib.dump(le_cpu, "cpu_encoder.lib")

['cpu_encoder.lib']

In [183]:
# Create unique encoder
le_op = LabelEncoder()
# Transform data
char['OpSys'] = le_op.fit_transform(char['OpSys'])
# Save file
joblib.dump(le_op, "op_encoder.lib")

['op_encoder.lib']

In [184]:
# Create unique encoder
le_gpu = LabelEncoder()
# Transform data
char['Gpu'] = le_gpu.fit_transform(char['Gpu'])
# Save file
joblib.dump(le_gpu, "gpu_encoder.lib")
# Create unique encoder
le_memory = LabelEncoder()
# Transform data
char['Memory'] = le_memory.fit_transform(char['Memory'])
# Save file
joblib.dump(le_memory, "memory_encoder.lib")

['memory_encoder.lib']

In [185]:
# Create unique encoder
le_type = LabelEncoder()
# Transform data
char['TypeName'] = le_type.fit_transform(char['TypeName'])
# Save file
joblib.dump(le_type, "type_encoder.lib")

['type_encoder.lib']

In [186]:
# Create unique encoder
le_company = LabelEncoder()
# Transform data
char['Company'] = le_company.fit_transform(char['Company'])
# Save file
joblib.dump(le_company, "company_encoder.lib")

['company_encoder.lib']

In [187]:
clean_data =pd.concat([char, num], axis=1)

In [188]:
clean_data

,Company,TypeName,ScreenResolution,Cpu,Memory,Gpu,OpSys,Inches,Ram,Weight,Price
0,1,4,23,65,4,58,8,13.3,8,1.37,71378.6832
1,1,4,1,63,2,51,8,13.3,8,1.34,47895.5232
2,7,3,8,74,16,53,4,15.6,8,1.86,30636.0000
3,1,4,25,85,29,9,8,15.4,16,1.83,135195.3360
4,1,4,23,67,16,59,8,13.3,8,1.37,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1298,10,0,13,89,4,47,5,14.0,4,1.80,33992.6400
1299,10,0,19,89,29,47,5,13.3,16,1.30,79866.7200
1300,10,3,0,34,35,40,5,14.0,2,1.50,12201.1200
1301,7,3,0,89,10,21,5,15.6,6,2.19,40705.9200
1302,2,3,0,34,26,40,5,15.6,4,2.20,19660.3200

In [189]:
clean_data.to_csv('new_cleaned_laptop_data.csv')

In [190]:
x=clean_data.drop('Price',axis=1)

In [191]:
y=clean_data['Price']

In [192]:
x

,Company,TypeName,ScreenResolution,Cpu,Memory,Gpu,OpSys,Inches,Ram,Weight
0,1,4,23,65,4,58,8,13.3,8,1.37
1,1,4,1,63,2,51,8,13.3,8,1.34
2,7,3,8,74,16,53,4,15.6,8,1.86
3,1,4,25,85,29,9,8,15.4,16,1.83
4,1,4,23,67,16,59,8,13.3,8,1.37
...,...,...,...,...,...,...,...,...,...,...
1298,10,0,13,89,4,47,5,14.0,4,1.80
1299,10,0,19,89,29,47,5,13.3,16,1.30
1300,10,3,0,34,35,40,5,14.0,2,1.50
1301,7,3,0,89,10,21,5,15.6,6,2.19
1302,2,3,0,34,26,40,5,15.6,4,2.20

In [193]:
y

0        71378.6832
1        47895.5232
2        30636.0000
3       135195.3360
4        96095.8080
           ...
1298     33992.6400
1299     79866.7200
1300     12201.1200
1301     40705.9200
1302     19660.3200
Name: Price, Length: 1303, dtype: float64

In [194]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)  ## Here we are splitting the data into training and testing data. test_size=0.2 means 20% of the data will be used for testing and 80% will be used for training. random_state=42 means we are using a random seed of 42 to get the same result every time we run the code.

In [195]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(x_train , y_train)

SVR()

In [196]:
svr.score(x_test , y_test)  ## Here we are checking the accuracy of the model. The score method returns the coefficient of determination R^2 of the prediction. The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). A constant model that always predicts the expected value of y, disregarding the input features, would get a R^2 score of 0.0.

-0.027543944402208975

In [197]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train , y_train)

LinearRegression()

In [198]:
lr.score(x_test , y_test)  ## Here we are checking the accuracy of the model. The score method returns the coefficient of determination R^2 of the prediction. The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). A constant model that always predicts the expected value of y, disregarding the input features, would get a R^2 score of 0.0.

0.6363135416868162

In [199]:
lr.score(x_train , y_train)  ## Here we are checking the accuracy of the model. The score method returns the coefficient of determination R^2 of the prediction. The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). A constant model that always predicts the expected value of y, disregarding the input features, would get a R^2 score of 0.0.

0.6795946863181856

In [200]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train , y_train)

RandomForestRegressor()

In [201]:
model.score(x_test , y_test)  ## Here we are checking the accuracy of the model. The score method returns the coefficient of determination R^2 of the prediction. The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). A constant model that always predicts the expected value of y, disregarding the input features, would get a R^2 score of 0.0.

0.8297795543632557

In [202]:
from sklearn.ensemble import GradientBoostingRegressor

# 1. Initialize the model
model = GradientBoostingRegressor(n_estimators=300,random_state=42)

# 2. Train the model
model.fit(x_train, y_train)

GradientBoostingRegressor(n_estimators=300, random_state=42)

In [203]:
model.score(x_test , y_test)  ## Here we are checking the accuracy of the model. The score method returns the coefficient of determination R^2 of the prediction. The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). A constant model that always predicts the expected value of y, disregarding the input features, would get a R^2 score of 0.0.

0.8707036227571769

In [204]:
import joblib
joblib.dump(model, "laptop_price_predictor_model.lib")

['laptop_price_predictor_model.lib']

In [205]:
import joblib
import pandas as pd
model=joblib.load('laptop_price_predictor_model.lib')
  ## Here we are loading the model from the file named laptop_price_predictor_model.lib using joblib library.
le_company=joblib.load('company_encoder.lib')
le_op=joblib.load('op_encoder.lib')
le_cpu=joblib.load('cpu_encoder.lib')
le_gpu=joblib.load('gpu_encoder.lib')
le_memory=joblib.load('memory_encoder.lib')
le_type=joblib.load('type_encoder.lib')
le_screen=joblib.load('screen_resolution_encoder.lib')

In [206]:
new_laptop = {
    'Company': 'HP',
    'TypeName': 'Notebook',
    'Inches': 15.6,
    'ScreenResolution': 'Full HD 1920x1080',
    'Cpu': 'Intel Core i5 7200U 2.5GHz',
    'Ram': 8,              # Already numeric
    'Memory': '256GB SSD', # Make sure this matches your final numeric column layout!
    'Gpu': 'Intel HD Graphics 620',
    'OpSys': 'Windows 10',
    'Weight': 1.86         # Already numeric
}
input_df=pd.DataFrame([new_laptop])  ## Here we are creating a new data frame from the new_laptop dictionary. The pd.DataFrame() function is used to create a data frame from a dictionary. The [new_laptop] is used to create a list of dictionaries. The list of dictionaries is used to create a data frame.

In [207]:
input_df['Company'] = le_company.transform(input_df['Company'])
input_df['OpSys'] = le_op.transform(input_df['OpSys'])
input_df['Cpu'] = le_cpu.transform(input_df['Cpu'])
input_df['Gpu'] = le_gpu.transform(input_df['Gpu'])
input_df['Memory'] = le_memory.transform(input_df['Memory'])
input_df['TypeName'] = le_type.transform(input_df['TypeName'])
input_df['ScreenResolution'] = le_screen.transform(input_df['ScreenResolution'])

In [210]:
# 1. Force the columns to match the exact order of your training dataset
feature_order = list(x_train.columns)
input_df = input_df[feature_order]

# 2. Now run the prediction (it will execute perfectly!)
predicted_price = model.predict(input_df)[0]

In [214]:


# 2. Print a clean, formatted receipt of the laptop details and its prediction
print("=" * 45)
print("       LAPTOP PRICE PREDICTION OUTPUT        ")
print("=" * 45)
print(f" 🏢 Company:          {new_laptop['Company']}")
print(f" 💻 Type:             {new_laptop['TypeName']}")
print(f" 📏 Screen Size:      {new_laptop['Inches']} inches")
print(f" 🖥️ Resolution:     {new_laptop['ScreenResolution']}")
print(f" 🧠 Processor (CPU):  {new_laptop['Cpu']}")
print(f" 💾 RAM Capacity:     {new_laptop['Ram']} GB")
print(f" 🗄️ Storage (Memory): {new_laptop['Memory']}")
print(f" 🎮 Graphics (GPU):   {new_laptop['Gpu']}")
print(f" 💿 Operating System: {new_laptop['OpSys']}")
print(f" ⚖️ Weight:           {new_laptop['Weight']} kg")
print("-" * 45)
print(f" 💰 PREDICTED PRICE:  {predicted_price:,.4f}")
print("=" * 45)

=============================================
       LAPTOP PRICE PREDICTION OUTPUT
=============================================
 🏢 Company:          HP
 💻 Type:             Notebook
 📏 Screen Size:      15.6 inches
 🖥️ Resolution:     Full HD 1920x1080
 🧠 Processor (CPU):  Intel Core i5 7200U 2.5GHz
 💾 RAM Capacity:     8 GB
 🗄️ Storage (Memory): 256GB SSD
 🎮 Graphics (GPU):   Intel HD Graphics 620
 💿 Operating System: Windows 10
 ⚖️ Weight:           1.86 kg
---------------------------------------------
 💰 PREDICTED PRICE:  47,587.8088
=============================================